### ISSUE TITLE
Permettre à un utilisateur de devenir artiste

### ISSUE THREAD

**Issue by Noampsg935** [YannoteX/Site_web_S4#10]
Avec les options spécifiques aux artistes : Biographie, accepter d'être contacté ( si  oui leurs contacts) .....

**Comment by YannoteX** [comment]
Tout les utilisateurs sont des artistes. Ils choisissent de poster ou non des images.

**Comment by YannoteX** [comment]
Tout les utilisateurs sont des artistes, ils choisissent de poster ou non
