### ISSUE TITLE
Création de filtres pour chercher des images

### ISSUE THREAD

**Issue by Noampsg935** [YannoteX/Site_web_S4#6]
Création de filtres pour classer les photos selon certain criteres (dates de mises en ligne, leurs volumes ou encore leurs prix etc...)
Pour faciliter la fluidité.

**Comment by YannoteX** [comment]
added api function to find images by keywords or/and by tags

**Comment by YannoteX** [comment]
La page photo servira a télécharger l'image, celles-ci seront triées dans la page d'acceuil

**Comment by YannoteX** [comment]
fonctionnels
